Update Register Display Text
sumuttekno/kokoru pull request #7
Opened 2017-11-25 06:01 UTC by jonathannatanaelsiahaan

2017-11-25 06:29 UTC, jonathannatanaelsiahaan commented
Please review so it can merging faster

2017-11-25 10:36 UTC, bxcodec requested changes
`public/bin/index.bundle.js.gz` 
Is this file generated?

Who will generate it?  If it generated by code or cli, and can be automated, please put this file into `.gitignore`

2017-11-25 10:36 UTC, bxcodec commented on public/bin/index.bundle.js
> +var _defineProperty = __webpack_require__(209);
what does this value do? `209`

2017-11-25 10:36 UTC, bxcodec commented on public/bin/index.bundle.js
> +var _warning = __webpack_require__(9);
what does this number do?

2017-11-25 10:36 UTC, bxcodec commented on public/bin/index.bundle.js
> +var _warning = __webpack_require__(9);
same here

2017-11-25 10:37 UTC, bxcodec commented
What really this things do ? :D 
Every number in webpack

2017-11-25 14:37 UTC, jonathannatanaelsiahaan commented
All file inside bin folder is generated by webpack. I already create pull request about that

2017-11-25 14:39 UTC, jonathannatanaelsiahaan commented
You can refer to another pr

2017-11-26 03:20 UTC, bxcodec approved these changes

2017-11-26 03:21 UTC, bxcodec commented
LGTM

2017-11-26 03:26 UTC, merged